// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhPMcgXsNPxDy0D5VwULhCE3xiDZXgMgg',
    appId: '1:1077099428914:web:782e32e2714b08e09a902b',
    messagingSenderId: '1077099428914',
    projectId: 'p3l-notif',
    authDomain: 'p3l-notif.firebaseapp.com',
    storageBucket: 'p3l-notif.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB397itiuLyEuNDvjZR93Sb1PQLTAF93p8',
    appId: '1:1077099428914:android:4396a2196ed7d31c9a902b',
    messagingSenderId: '1077099428914',
    projectId: 'p3l-notif',
    storageBucket: 'p3l-notif.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM050BSix4DcTP6w-dDTNKGBoigv4Vfxo',
    appId: '1:1077099428914:ios:f8cdd1fdcea820639a902b',
    messagingSenderId: '1077099428914',
    projectId: 'p3l-notif',
    storageBucket: 'p3l-notif.appspot.com',
    iosBundleId: 'com.example.atmaKitchenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM050BSix4DcTP6w-dDTNKGBoigv4Vfxo',
    appId: '1:1077099428914:ios:f8cdd1fdcea820639a902b',
    messagingSenderId: '1077099428914',
    projectId: 'p3l-notif',
    storageBucket: 'p3l-notif.appspot.com',
    iosBundleId: 'com.example.atmaKitchenApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhPMcgXsNPxDy0D5VwULhCE3xiDZXgMgg',
    appId: '1:1077099428914:web:cb082d9461a0966e9a902b',
    messagingSenderId: '1077099428914',
    projectId: 'p3l-notif',
    authDomain: 'p3l-notif.firebaseapp.com',
    storageBucket: 'p3l-notif.appspot.com',
  );
}
